dist: bionic

branches:
  only:
    - master

sudo: false

notifications:
  email:
    on_failure: change

matrix:
  include:
    - language: cpp
      os: linux
      script:
        - mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DASAN=ON
        - make -j$(nproc) && ./tests

    - language: cpp
      os: osx
      script:
        - mkdir -p build && cd build &&  cmake .. -DCMAKE_BUILD_TYPE=Debug
        - make -j$(nproc) && ./tests

    - language: python
      os: linux
      python: "3.7"
      install:
        - pip install -r python/requirements.txt -r python/test/requirements.txt
        - cd python && python setup.py install
      script: pytest

    - language: minimal
      os: osx
      osx_image: xcode10.2
      name: "Python 3.7"
      install:
        - python --version
        - python3 --version
        - pip3 install -r python/requirements.txt -r python/test/requirements.txt
        - cd python && python3 setup.py install
      script: pytest

    - language: julia
      os: linux
      julia: 1.2
      script:
        - julia --project=julia --color=yes -e "using Pkg; Pkg.instantiate();"
        - julia --project=julia --color=yes -e "using Pkg; Pkg.build();"
        - julia --project=julia --color=yes -e "using Pkg; Pkg.test()"
        - julia --project=docs/ --color=yes docs/make.jl
 
    - language: rust
      os: linux
      rust: stable
      script:
        - cargo --version
        - cargo test
