dist: bionic

branches:
  only:
    - master

sudo: false

notifications:
  email:
    on_failure: change

matrix:
  include:
    - language: cpp
      os: linux
      script:
        - mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DASAN=ON
        - make -j$(nproc) && ./tests

    - language: cpp
      os: osx
      script:
        - mkdir -p build && cd build &&  cmake .. -DCMAKE_BUILD_TYPE=Debug
        - make -j$(nproc) && ./tests

    - language: python
      python: "3.7"
      install:
        - cd python && python setup.py install
      script: pytest

    - language: julia
      os: linux  # don't need it specifically for osx
      julia: 1.2
      script:
        - julia -e 'import Pkg; Pkg.develop(Pkg.PackageSpec(path="julia"))'
        - julia -e 'import Pkg; Pkg.instantiate()'
        - julia -e 'import Pkg; Pkg.build("GraphIdx")'
        - julia --color=yes -e 'import Pkg; Pkg.test("GraphIdx")'
        - julia --project=docs/ -e 'import Pkg; Pkg.add("Documenter")'
        - julia --project=docs/ --color=yes docs/make.jl
 
    - language: rust
      os: linux
      rust: stable
      script:
        - cargo --version
        - cargo test
