[package]
name = "graphidx"
version = "0.1.3"
authors = ["Elias Kuthe <elias.kuthe@tu-dortmund.de>"]
edition = "2018"
exclude = ["../deps/**"]
keywords = ["algorithm", "graph", "data-structure", "unionfind", "index"]

[dependencies]
