name: RustCI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    name: Rust graphidx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test
